general {
    lock_cmd = pidof hyprlock || ~/.local/bin/hyprlock-wrapper    # Kilitleme komutu
    before_sleep_cmd = loginctl lock-session                      # Uyku öncesi kilitle
    after_sleep_cmd = hyprctl dispatch dpms on                    # Uyandığında ekranı aç
    ignore_dbus_inhibit = false
}

# Ekran Parlaklığını Düşür (2.5 dk)
listener {
    timeout = 150
    on-timeout = brightnessctl set 10%
    on-resume = brightnessctl set 100%
}

# Kilitle (5 dk)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Monitörü Kapat (5.5 dk)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl set 100%
}

# Sistemi Askıya Al (30 dk)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
